CREATE TABLE settings(id INTEGER PRIMARY KEY CHECK(id=1), enabled INTEGER NOT NULL DEFAULT 0, revision TEXT NOT NULL DEFAULT '', sealed TEXT);
INSERT INTO settings(id) VALUES(1);
CREATE TABLE campaigns(media_id TEXT PRIMARY KEY, data TEXT NOT NULL);
CREATE TABLE jobs(id TEXT PRIMARY KEY, media_id TEXT NOT NULL, text TEXT NOT NULL, state TEXT NOT NULL, created INTEGER NOT NULL, due INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, detail TEXT NOT NULL DEFAULT '', revision TEXT NOT NULL);
CREATE INDEX jobs_due ON jobs(state,due);
CREATE INDEX jobs_created ON jobs(created DESC);
CREATE TABLE daily(day TEXT PRIMARY KEY, requests INTEGER NOT NULL DEFAULT 0, sends INTEGER NOT NULL DEFAULT 0);
CREATE TABLE locks(id INTEGER PRIMARY KEY CHECK(id=1), token TEXT NOT NULL, expires INTEGER NOT NULL);
