import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {createHmac} from 'node:crypto';
import {admit,REQUEST_LIMIT,createWorker,locked,processOne,ingest} from './worker.mjs';
class D1 {
 constructor(){this.db=new DatabaseSync(':memory:');this.db.exec(readFileSync(new URL('./migrations/0001.sql',import.meta.url),'utf8'));}
 prepare(sql){let args=[];const db=this.db;const result=()=>{const s=db.prepare(sql);const rows=s.columns().length?s.all(...args):[];let changes=0;if(!s.columns().length)changes=s.run(...args).changes;else if(/^(INSERT|UPDATE|DELETE)/i.test(sql.trim()))changes=db.prepare('SELECT changes() AS n').get().n;return {results:rows,meta:{changes},success:true};};return {bind(...a){args=a;return this;},async first(){return result().results[0]||null;},async all(){return result();},async run(){return result();}};}
 async batch(queries){this.db.exec('BEGIN');try{const results=[];for(const q of queries)results.push(await q.run());this.db.exec('COMMIT');return results;}catch(e){this.db.exec('ROLLBACK');throw e;}}
}
const env=db=>({DB:db,ADMIN_TOKEN:'a'.repeat(40),SETTINGS_KEY:'k'.repeat(40),META_VERIFY_TOKEN:'verify'});
const request=(path,body)=>new Request('https://example.com'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+'a'.repeat(40),'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
const input={account:'123',username:'butai',version:'v24.0',token:'token-secret',secret:'app-secret',verify:'verify',dryRun:false};
const post={mediaId:'456',name:'募集',keywords:['舞台'],mode:'exact',message:'ご案内',lineUrl:'https://lin.ee/pgwER6s',enabled:true};
const payload=id=>({object:'instagram',entry:[{id:'123',changes:[{field:'comments',value:{id,text:'舞台',media:{id:'456'},from:{id:'789'}}}]}]});
async function setup(){const db=new D1(),e=env(db),w=createWorker();assert.equal((await w.fetch(request('/api/connection',input),e)).status,200);assert.equal((await w.fetch(request('/api/campaigns',post),e)).status,200);assert.equal((await w.fetch(request('/api/enabled',{enabled:true}),e)).status,200);return {db,e,w};}
async function webhook(w,e,id){const text=JSON.stringify(payload(id));return w.fetch(new Request('https://example.com/webhook',{method:'POST',headers:{'Content-Type':'application/json','X-Hub-Signature-256':'sha256='+createHmac('sha256','app-secret').update(text).digest('hex')},body:text}),e);}
test('atomic daily gate admits only remaining tickets concurrently and resets at UTC midnight',async()=>{const db=new D1(),now=Date.parse('2026-10-07T23:59:59Z');db.db.prepare('INSERT INTO daily VALUES(?,?,0)').run('2026-10-07',REQUEST_LIMIT-2);const results=await Promise.all(Array.from({length:10},()=>admit(db,now)));assert.equal(results.filter(Boolean).length,2);assert.equal(db.db.prepare('SELECT requests FROM daily').get().requests,REQUEST_LIMIT);assert.equal(await admit(db,now+1000),true);});
test('webhook and scheduled send both stop at budget, while DB failure fails closed',async()=>{const {db,e,w}=await setup();const d=new Date().toISOString().slice(0,10);db.db.prepare('UPDATE daily SET requests=? WHERE day=?').run(REQUEST_LIMIT,d);assert.equal((await webhook(w,e,'1')).status,429);assert.equal(db.db.prepare('SELECT count(*) n FROM jobs').get().n,0);let calls=0;await createWorker(async()=>{calls++;}).scheduled({},e);assert.equal(calls,0);assert.equal((await w.fetch(request('/api/state'),e)).status,429);const bad={...e,DB:{prepare(){throw Error('D1 unavailable');}}};assert.equal((await w.fetch(request('/webhook',{}),bad)).status,503);await assert.rejects(w.scheduled({},bad));});
test('encrypted configuration, signed webhook, persistent dedupe and one correct private reply',async()=>{const {db,e,w}=await setup();const sealed=db.db.prepare('SELECT sealed FROM settings').get().sealed;assert.ok(!sealed.includes('token-secret'));const publicData=await (await w.fetch(request('/api/connection'),e)).json();assert.equal(publicData.token,undefined);assert.equal(publicData.hasToken,true);assert.equal((await webhook(w,e,'111')).status,200);assert.equal((await webhook(w,e,'111')).status,200);let calls=0;const worker=createWorker(async(url,opts)=>{calls++;assert.match(String(url),/\/123\/messages$/);const b=JSON.parse(opts.body);assert.deepEqual(b.recipient,{comment_id:'111'});assert.match(b.message.text,/https:\/\/lin.ee\/pgwER6s/);return Response.json({message_id:'m1'});});await worker.scheduled({},e);await worker.scheduled({},e);assert.equal(calls,1);assert.equal(db.db.prepare('SELECT state FROM jobs').get().state,'sent');assert.equal((await w.fetch(new Request('https://example.com/api/state'),e)).status,401);});
test('global lock excludes concurrent delivery and mutations; uncertain result never replays',async()=>{const {db,e,w}=await setup();await webhook(w,e,'222');let release;const barrier=new Promise(r=>release=r);let calls=0;const worker=createWorker(async()=>{calls++;await barrier;throw Error('network');});const sending=worker.scheduled({},e);while(!calls)await new Promise(r=>setTimeout(r,1));await worker.scheduled({},e);assert.equal((await w.fetch(request('/api/connection',input),e)).status,409);release();await sending;await worker.scheduled({},e);assert.equal(calls,1);assert.equal(db.db.prepare('SELECT state FROM jobs').get().state,'uncertain');});
test('send attempt cap, account switching and stopped post preserve isolation',async()=>{const {db,e,w}=await setup();await webhook(w,e,'333');const d=new Date().toISOString().slice(0,10);db.db.prepare('UPDATE daily SET sends=1000 WHERE day=?').run(d);let calls=0;await createWorker(async()=>{calls++;}).scheduled({},e);assert.equal(calls,0);assert.equal(db.db.prepare('SELECT state FROM jobs').get().state,'pending');assert.equal((await w.fetch(request('/api/connection',{...input,account:'999'}),e)).status,200);assert.equal(db.db.prepare('SELECT count(*) n FROM campaigns').get().n,0);assert.equal(db.db.prepare('SELECT state FROM jobs').get().state,'cancelled');assert.equal((await webhook(w,e,'444')).status,200);assert.equal(db.db.prepare('SELECT count(*) n FROM jobs').get().n,1);});
test('stale webhook settings cannot enqueue after an account revision change',async()=>{const db=new D1();db.db.prepare("UPDATE settings SET enabled=1,revision='new' WHERE id=1").run();db.db.prepare('INSERT INTO campaigns VALUES(?,?)').run('456',JSON.stringify(post));assert.equal(await ingest(db,payload('5'),{account:'123',enabled:true,revision:'old',dryRun:false},Date.now()),0);});
